# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='rating',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='join',
            name='review',
            field=models.TextField(default='SOME STRING', max_length=350),
        ),
    ]
