# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_trip_tripuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='datefrom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dateto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
