# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_auto_20170127_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='userid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
