# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_trip_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripmanager',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripmanager',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='tripuser1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1user', to='travel_app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='usertrip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip2user', to='travel_app.Trip'),
        ),
        migrations.DeleteModel(
            name='Tripmanager',
        ),
    ]
