# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_auto_20170127_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='tripuser',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='userid',
        ),
    ]
