# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_auto_20170127_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='datefrom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dateto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tripuser1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1user', to='travel_app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertrip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip2user', to='travel_app.Trip'),
        ),
    ]
